version: '3'
services:
  mysql_dev:
    image: mysql:8.0
    container_name: dojoohwan_mysql_dev
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: 'meeting'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      TZ: 'Asia/Seoul'
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d

  mysql_prod:
    image: mysql:8.0
    container_name: dojoohwan_mysql_prod
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: 'meeting'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      TZ: 'Asia/Seoul'
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
